Upcoming Events UI
islanddrago/Event-bay pull request #26
Opened 2019-11-22 04:49 UTC by joe-niu

2019-11-23 23:24 UTC, mcjcloud requested changes

2019-11-23 23:24 UTC, mcjcloud commented on ebay-frontend/src/app/app.component.ts
> +import {FlexLayoutModule} from '@angular/flex-layout';
You shouldn't need FlexLayoutModule

2019-11-23 23:24 UTC, mcjcloud commented on ebay-frontend/package.json
> +    "@angular/flex-layout": "^8.0.0-beta.27",
You shouldn't need flex-layout here

2019-11-23 23:24 UTC, mcjcloud commented on ebay-frontend/src/app/upcoming-events-screen/upcoming-events-screen.component.html
> +<button mat-fab class="createEventButton"> + </button>
Use material icon here instead of "+", also clean up formatting in this file

2019-11-23 23:24 UTC, mcjcloud commented on ebay-frontend/src/app/upcoming-events-screen/upcoming-events-screen.component.scss
> +  background: white;
you shouldn't need to set the background color for left and right if you're setting it for .upcoming-card

2019-11-23 23:24 UTC, mcjcloud commented on ebay-frontend/src/app/upcoming-events-screen/upcoming-events-screen.component.scss
> +  line-height: 100px;
`line-height: 100px` doesn't scale very well. Try `align-items: center` to make the text stay in the middle

2019-11-23 23:24 UTC, mcjcloud commented on ebay-frontend/src/app/upcoming-events-screen/upcoming-events-screen.component.scss
> +.createEventButton {
None of these except the last three should be needed if you're using mat-fab-button correctly

2019-11-23 23:24 UTC, mcjcloud commented on ebay-frontend/src/app/upcoming-events-screen/upcoming-events-screen.component.scss
> +.createEventButton:hover {
Material handles this for us

2019-11-23 23:24 UTC, mcjcloud commented on ebay-frontend/src/app/upcoming-events-screen/upcoming-events-screen.component.scss
> +.upcoming-card:hover {
Material handles this

2019-11-24 04:18 UTC, joe-niu commented
Just now pushed implemented change requests.

2019-11-24 04:21 UTC, mcjcloud approved these changes

2019-11-24 04:35 UTC, merged