Adding Create Events screen page
islanddrago/Event-bay pull request #30
Opened 2019-11-30 05:38 UTC by joe-niu

2019-11-30 19:31 UTC, mcjcloud requested changes

2019-11-30 19:31 UTC, mcjcloud commented on ebay-frontend/src/app/upcoming-events-screen/upcoming-events-screen.component.html
> +<a routerLink="/create-events" routerLinkActive=""><button mat-fab color=primary class="createEventButton"> <mat-icon>add</mat-icon> </button></a>
You shouldn't need to surround the button with an `a` tag. You should be able to put `routerLink` directly on the button. Also, you shouldn't need the `routerLinkActive` unless you're going to enable/disable it.

2019-11-30 19:31 UTC, mcjcloud commented on ebay-frontend/src/app/create-events-screen/create-events-screen.component.scss
> +.form-container {
Formatting needs to be fixed in this file

2019-11-30 19:31 UTC, mcjcloud commented on ebay-frontend/src/app/create-events-screen/create-events-screen.component.html
> +<div class="form-container">
Formatting needs to be fixed in this file

2019-11-30 19:31 UTC, mcjcloud commented on ebay-frontend/src/app/app-routing.module.ts
> +import { CreateEventsScreenComponent } from './create-events-screen/create-events-screen.component';
`CreateEventsScreen` should just be called `CreateEventScreen` because you're only creating one event at a time.

2019-11-30 23:25 UTC, joe-niu commented
Implemented change requests.

2019-12-01 01:20 UTC, mcjcloud approved these changes

2019-12-01 01:20 UTC, merged